### ISSUE TITLE
Cannot find module '../Views/design/color'

### ISSUE THREAD

**Issue by Ethan-Hill** [oppsec/Discor#5]
Its currently looking for a file that does not exist in the folder.

![code](https://user-images.githubusercontent.com/45304268/97796950-1ad2a900-1c10-11eb-971e-d8a6247bf0fc.png)

**Comment by oppsec** [comment]
I think you got confused because this module does exist

![image](https://user-images.githubusercontent.com/50470310/97804986-03a4b300-1c32-11eb-91a4-efc6bcf9bb82.png)

And I don't need to specific the .js

**Comment by oppsec** [comment]
Thanks for warning me about that, I already upload a release which this issue is fixed.
